In [6]:
import pandas as pd

In [8]:
file_path = "Base Risk Lexicon 2021 - Triggers.csv"
df = pd.read_csv(file_path)
df

,keywords,labels,weight,distance,range,Notes?,Unnamed: 6,Unnamed: 7
0,authority authorities government sec && on && ...,authorities-action,-300.0,12.0,10.0,NaN,NaN,NaN
1,authority authorities government sec && prepar...,authorities-action,-300.0,12.0,10.0,NaN,NaN,NaN
2,diversity-inclusion,authorities-action,-300.0,25.0,5.0,NaN,labels,how many lines?
3,banking bank need needs needing billion bln bi...,authorities-action,-300.0,25.0,5.0,NaN,authorities-action,13
4,bankrupt bankruptcy failliet failliete faillit...,authorities-action,-400.0,25.0,6.0,NaN,bad-workplace-conditions,2
...,...,...,...,...,...,...,...,...
5699,smeergeld,smeergeld,NaN,NaN,NaN,NaN,NaN,NaN
5700,misda,misda,NaN,NaN,NaN,NaN,NaN,NaN
5701,offshore && leaks,offshore-leaks,NaN,NaN,NaN,NaN,NaN,NaN
5702,hoger && beroep,hoger-beroep,NaN,NaN,NaN,NaN,NaN,NaN
5703,belastingont,belastingont,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
average_values = df.groupby('labels')['weight'].mean().reset_index()
average_values = average_values.sort_values(by='weight', ascending=True)
average_values = average_values.dropna(subset=['weight'])

                                                labels      weight
222                                positive regulatory  150.000000
220                        pos-future-outlook positive  140.000000
221                                           positive   80.398671
208  political-accountability \nenvironmental-impac...   70.000000
223                            positive strategic-risk   60.000000
..                                                 ...         ...
301                                        veroordeeld         NaN
302                                         vervolging         NaN
303                                     voorwetenschap         NaN
306                                          witwassen         NaN
310                                            xtc-lab         NaN

[311 rows x 2 columns]